### ISSUE TITLE
[BUG] Email Reports HTTP 500 on email send

### ISSUE THREAD

**Issue by jsdokos** [TheSpaghettiDetective/obico-server#637]
**Note**
Most of the times, an issue you may potentially run into is not a bug. Instead, it is related to configurations, such as firewall rules, incompatible docker version, reverse proxy setups, etc.

If you are not sure, please don't open a bug report here. Instead, you can get the issue solved much faster by seeking help in our support forum: https://discord.gg/zvSzJea6as.

Proceed to opening a bug report only if you are sure it is a defect in the code given a correct configuration.
 
**Describe the bug**
When sending an email either from the test or verification GUI the django app errors out with the code below.
**To Reproduce**
1. See above.

**Screenshots**
`django.request ERROR    Internal Server Error: /accounts/email/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/allauth/account/views.py", line 419, in dispatch
    return super(EmailView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/allauth/account/views.py", line 448, in post
    res = self._action_send(request)
  File "/usr/local/lib/python3.7/site-packages/allauth/account/views.py", line 476, in _action_send
    email_address.send_confirmation(request)
  File "/usr/local/lib/python3.7/site-packages/allauth/account/models.py", line 62, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/usr/local/lib/python3.7/site-packages/allauth/account/models.py", line 169, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/usr/local/lib/python3.7/site-packages/allauth/account/adapter.py", line 464, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/usr/local/lib/python3.7/site-packages/allauth/account/adapter.py", line 136, in send_mail
    msg.send()
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/message.py", line 306, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -8] Unrecognized service
django.channels.server ERROR    HTTP POST /accounts/email/ 500 [0.22, 192.168.50.31:61615]`

**Hosting environment (please complete the following information):**
 - OS: Debian 11.3
 - Hardware Mini PC

**Additional context**
Seems to have something to do with the move to .env, it was working before then, but i'm not sure. Issue persisted on a clean debian install.

**Comment by jsdokos** [comment]
This is also a copy of the error: https://pastebin.com/y2d4KA9H

**Comment by kennethjiang** [comment]
Sorry for missing your issue.

But this looks like an environment issue. Please seek help on our discord server. Users there seem to have run into a similar issue. Maybe you can help each other: https://discord.com/channels/614543405724205137/648759742881071124/974020883633021038
