### ISSUE TITLE
Broken TSD Docker deployment

### ISSUE THREAD

**Issue by mcstoufer** [TheSpaghettiDetective/obico-server#658]
I just pulled the latest Obico plugin (2.10) for Octoprint (1.8.1) and that update worked just fine. I also have a docker container running near the octoprint server on a Mac. I git pulled the latest release HEAD from the TSD repo and updated the container. When, the container comes up, I'm seeing some Python level issues with modules not being found in the _web and _tasks containers. 
This module is in the requirements.txt file. Since the container is continually restarting, I can 'docker exec' into it and verify the module is somewhere in the site-packaages scope.
Any ideas?

```
thespaghettidetective-web-1 | During handling of the above exception, another exception occurred:
thespaghettidetective-web-1 | 
thespaghettidetective-web-1 | Traceback (most recent call last):
thespaghettidetective-web-1 |   File "manage.py", line 15, in <module>
thespaghettidetective-web-1 |     execute_from_command_line(sys.argv)
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
thespaghettidetective-web-1 |     utility.execute()
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
thespaghettidetective-web-1 |     self.fetch_command(subcommand).run_from_argv(self.argv)
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 336, in run_from_argv
thespaghettidetective-web-1 |     connections.close_all()
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 219, in close_all
thespaghettidetective-web-1 |     for alias in self:
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 213, in __iter__
thespaghettidetective-web-1 |     return iter(self.databases)
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
thespaghettidetective-web-1 |     res = instance.__dict__[self.name] = self.func(instance)
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 147, in databases
thespaghettidetective-web-1 |     self._databases = settings.DATABASES
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
thespaghettidetective-web-1 |     self._setup(name)
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
thespaghettidetective-web-1 |     self._wrapped = Settings(settings_module)
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
thespaghettidetective-web-1 |     mod = importlib.import_module(self.SETTINGS_MODULE)
thespaghettidetective-web-1 |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
thespaghettidetective-web-1 |     return _bootstrap._gcd_import(name[level:], package, level)
thespaghettidetective-web-1 |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
thespaghettidetective-web-1 |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
thespaghettidetective-web-1 |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
thespaghettidetective-web-1 |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
thespaghettidetective-web-1 |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
thespaghettidetective-web-1 |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
thespaghettidetective-web-1 |   File "/app/config/settings.py", line 5, in <module>
thespaghettidetective-web-1 |     import sentry_sdk
thespaghettidetective-web-1 | ModuleNotFoundError: No module named 'sentry_sdk'
```

**Comment by mcstoufer** [comment]
Closing this issue. I had missed that the repos had changed and was thus pulling content from the older repo. A checkout of the newer one with the same instructions got me back on track.

**Comment by MikeFez** [comment]
@mcstoufer Would you mind clarifying this? I've pulled via `git clone -b release https://github.com/TheSpaghettiDetective/obico-server.git` as described in the readme and I'm having the same issue.

**Comment by kennethjiang** [comment]
> @mcstoufer Would you mind clarifying this? I've just pulled via `git clone -b release https://github.com/TheSpaghettiDetective/obico-server.git` as described in the readme contained within this repo and I'm having the same issue.

I couldn't reproduce it on my Mac. Please list:

- The OS/version of the host
- Docker/docker-compose versions.

**Comment by MikeFez** [comment]
Hi @kennethjiang! Sorry for the late reply, I've been away on a trip. I actually resolved my issue this morning - I hadn't noticed the docker-compose v2 requirement. Thank you!
