### ISSUE TITLE
docker web container: ValueError: Couldn't load manifest 'staticfiles.json' (version 1.0)

### ISSUE THREAD

**Issue by YaphetS1** [TheSpaghettiDetective/obico-server#839]
Hi, just reboot my machine after linked with moonraker-obiko. Remove backend/db.sqlite3 doesn't give any result

```
Operations to perform:
  Apply all migrations: account, admin, app, auth, channels_presence, contenttypes, sessions, sites, socialaccount
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 162, in handle
    if self.is_local_storage() and self.storage.location:
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 216, in is_local_storage
    return isinstance(self.storage, FileSystemStorage)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 498, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/usr/local/lib/python3.7/site-packages/whitenoise/storage.py", line 129, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 377, in __init__
    self.hashed_files = self.load_manifest()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 399, in load_manifest
    (self.manifest_name, self.manifest_version))
ValueError: Couldn't load manifest 'staticfiles.json' (version 1.0)
Operations to perform:
  Apply all migrations: account, admin, app, auth, channels_presence, contenttypes, sessions, sites, socialaccount
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 162, in handle
    if self.is_local_storage() and self.storage.location:
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 216, in is_local_storage
    return isinstance(self.storage, FileSystemStorage)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 498, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/usr/local/lib/python3.7/site-packages/whitenoise/storage.py", line 129, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 377, in __init__
    self.hashed_files = self.load_manifest()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 399, in load_manifest
    (self.manifest_name, self.manifest_version))
ValueError: Couldn't load manifest 'staticfiles.json' (version 1.0)
```

**Comment by YaphetS1** [comment]
[compose.log](https://github.com/TheSpaghettiDetective/obico-server/files/13419015/compose.log)

**Comment by YaphetS1** [comment]
Create thread in [discord](https://discord.com/channels/758059413700345988/1176256596544860221)

**Comment by YaphetS1** [comment]
After a lot of looking around, this worked for me: Remove all the files starting with staticfiles* and rebuild your app. 
`sudo rm backend/static_build/staticfiles*`
